EOL: updates to reflect EOL status.
newrelic/c-sdk pull request #35
Opened 2022-06-29 22:55 UTC by zsistla

2022-06-29 22:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/c-sdk?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/c-sdk?pullRequest=35) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/c-sdk?pullRequest=35) it.</sub>

2022-06-29 23:02 UTC, Ak-x approved these changes

2022-06-30 15:41 UTC, misiekn requested changes
This looks good. There are a few typos in the URLs that show `404 - Page not found` page instead of intended resource.

2022-06-30 15:41 UTC, lavarou commented on CHANGELOG.md
> +As of June 30 2022 we are archiving the C-SDK project. Please explore the [option to use OpenTelemetry](https://github.com/newrelic/docs-website/blob/develop/docs/apm/agents/c-sdk/get-started/otel_cp
`option to use OpenTelemetry` link (https://github.com/newrelic/docs-website/blob/develop/docs/apm/agents/c-sdk/get-started/otel_cpp_example) gives me 404 - Not Found. Shouldn't this link point to https://docs.newrelic.com/docs/apm/agents/c-sdk/get-started/otel_cpp_example/?

2022-06-30 15:41 UTC, misiekn commented on CONTRIBUTING.md
>  1. Submit a [pull request](#pull-request-guidelines) or [issue](#filing-issues--bug-reports). For pull requests, please also:
Is this section applicable for archived projects? Is New Relic going to review and merge any incoming PRs?

2022-06-30 15:41 UTC, misiekn commented on GUIDE.md
> +As of June 30 2022 we are archiving the C-SDK project. Please explore the [option to use OpenTelemetry](https://github.com/newrelic/docs-website/blob/develop/docs/apm/agents/c-sdk/get-started/otel_cp
```suggestion
As of June 30 2022 we are archiving the C-SDK project. Please explore the [option to use OpenTelemetry](https://docs.newrelic.com/docs/apm/agents/c-sdk/get-started/otel_cpp_example/) as an alternative to send C++ telemetry data to New Relic. For more details, see our [Explorers Hub announcement](https://discuss.newrelic.com/t/q1-bulk-eol-announcement-fy23/181744).
```

2022-06-30 15:41 UTC, misiekn commented on CONTRIBUTING.md
> +As of June 30 2022 we are archiving the C-SDK project. Please explore the [option to use OpenTelemetry](https://github.com/newrelic/docs-website/blob/develop/docs/apm/agents/c-sdk/get-started/otel_cp
```suggestion
As of June 30 2022 we are archiving the C-SDK project. Please explore the [option to use OpenTelemetry](https://docs.newrelic.com/docs/apm/agents/c-sdk/get-started/otel_cpp_example/) as an alternative to send C++ telemetry data to New Relic. For more details, see our [Explorers Hub announcement](https://discuss.newrelic.com/t/q1-bulk-eol-announcement-fy23/181744).
```


```

2022-06-30 15:41 UTC, misiekn commented on CHANGELOG.md
> +As of June 30 2022 we are archiving the C-SDK project. Please explore the [option to use OpenTelemetry](https://github.com/newrelic/docs-website/blob/develop/docs/apm/agents/c-sdk/get-started/otel_cp
```suggestion
As of June 30 2022 we are archiving the C-SDK project. Please explore the [option to use OpenTelemetry](https://docs.newrelic.com/docs/apm/agents/c-sdk/get-started/otel_cpp_example/) as an alternative to send C++ telemetry data to New Relic. For more details, see our [Explorers Hub announcement](https://discuss.newrelic.com/t/q1-bulk-eol-announcement-fy23/181744).
```

2022-06-30 15:41 UTC, misiekn commented on README.md
> +As of June 30 2022 we are archiving the C-SDK project. Please explore the [option to use OpenTelemetry](https://github.com/newrelic/docs-website/blob/develop/docs/apm/agents/c-sdk/get-started/otel_cp
```suggestion
As of June 30 2022 we are archiving the C-SDK project. Please explore the [option to use OpenTelemetry](https://docs.newrelic.com/docs/apm/agents/c-sdk/get-started/otel_cpp_example/) as an alternative to send C++ telemetry data to New Relic. For more details, see our [Explorers Hub announcement](https://discuss.newrelic.com/t/q1-bulk-eol-announcement-fy23/181744).
```

2022-06-30 15:41 UTC, misiekn commented on README.md
> -
Is New Relic going to remove all C SDK documentation from their website? If no, then I'd suggest to leave these links in and only remove the link to `New Relic Community`.

2022-06-30 15:41 UTC, misiekn commented on README.md
> +We encourage your experiments to improve the C SDK in your personal forks.
I'd suggest reiterating what the `Archived` banner says:
> This project is read-only and available for cloning only. We encourage you to experiment with it in your fork however please keep in mind that there is neither a maintainer team nor support.

2022-06-30 15:41 UTC, misiekn commented on ROADMAP.md
> +As of June 30 2022 we are archiving the C-SDK project. Please explore the [option to use OpenTelemetry](https://github.com/newrelic/docs-website/blob/develop/docs/apm/agents/c-sdk/get-started/otel_cp
```suggestion
As of June 30 2022 we are archiving the C-SDK project. Please explore the [option to use OpenTelemetry](https://docs.newrelic.com/docs/apm/agents/c-sdk/get-started/otel_cpp_example/) as an alternative to send C++ telemetry data to New Relic. For more details, see our [Explorers Hub announcement](https://discuss.newrelic.com/t/q1-bulk-eol-announcement-fy23/181744).
```

2022-06-30 17:53 UTC, lavarou approved these changes

2022-06-30 17:58 UTC, merged